vim.g.mapleader = " "
vim.keymap.set("n", "<leader>pv", vim.cmd.Ex, {desc = 'back to [P]roject [V]iew'})
--moving lines
vim.keymap.set('v',"<A-k>", ":m '<-2<CR>gv=gv")
vim.keymap.set('v',"<A-j>", ":m '>+1<CR>gv=gv")

--vim.keymap.set({ "n", "v" }, "<leader>y", [["+y]])
--vim.keymap.set("n", "<leader>Y", [["+Y]])
--permette di sostituire la stringa selezionata
vim.keymap.set("n", "<leader>ss", [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]], { desc =  "[S]ubstitute [s]"})
--dead keys
vim.keymap.set('i', "'a", "á" )
vim.keymap.set('i', "`a", "à" )
vim.keymap.set('i', "'A", "Á" )
vim.keymap.set('i', "`A", "À" )
vim.keymap.set('i', "'c", "ç" )
vim.keymap.set('i', "'C", "Ç" )
vim.keymap.set('i', "'e", "é" )
vim.keymap.set('i', "`e", "è" )
vim.keymap.set('i', "'E", "É" )
vim.keymap.set('i', "`E", "È" )
vim.keymap.set('i', "'i", "í" )
vim.keymap.set('i', "`i", "ì" )
vim.keymap.set('i', "'I", "Í" )
vim.keymap.set('i', "`I", "Ì" )
vim.keymap.set('i', "'o", "ó" )
vim.keymap.set('i', "`o", "ò" )
vim.keymap.set('i', "'O", "Ó" )
vim.keymap.set('i', "`O", "Ò" )
vim.keymap.set('i', "'u", "ú" )
vim.keymap.set('i', "`u", "ù" )
vim.keymap.set('i', "'U", "Ú" )
vim.keymap.set('i', "`U", "Ù" )
